describe('Signup with valid details', () => {

it('verify sign up with valid credentials', () => {


cy.visit('https://automationexercise.com/login')
cy.get('[data-qa="signup-name"]').should('be.visible').and('be.empty').type('Elijah')
cy.get('[data-qa="signup-email"]').should('be.visible').and('be.empty').type('mine15@hee.com')
cy.get('[data-qa="signup-button"]').click().should('be.visible')
cy.get('.clearfix > :nth-child(3)').click().should('be.visible')
cy.get('[data-qa="password"]').should('be.visible').and('be.empty').type('elijah1234')
cy.get(':nth-child(6) > .row > :nth-child(1)').click().should('be.visible')
cy.get('[data-qa="days"]').select('5').should('be.visible')
cy.get('[data-qa="months"]').select('May').should('be.visible')
cy.get('[data-qa="years"]').select('1990').should('be.visible')
cy.get('[data-qa="first_name"]').should('be.visible').and('be.empty').type('Elijah')
cy.get('[data-qa="last_name"]').should('be.visible').and('be.empty').type('Hee')
cy.get('[data-qa="company"]').should('be.visible').and('be.empty').type('Helihjah Company')
cy.get('[data-qa="address"]').should('be.visible').and('be.empty').type('1, Ayobo street, Ishefun')
cy.get('[data-qa="address2"]').should('be.visible').and('be.empty').type('Ipaja-Ayobo')
cy.get('[data-qa="country"]').select('United States').should('be.visible')
cy.get('[data-qa="state"]').should('be.visible').and('be.empty').type('Lagos')
cy.get('[data-qa="city"]').should('be.visible').and('be.empty').type('Ayobo')
cy.get('[data-qa="zipcode"]').should('be.visible').and('be.empty').type('234')
cy.get('[data-qa="mobile_number"]').should('be.visible').type('09097957017')
cy.get('[data-qa="create-account"]').click().should('be.visible')
cy.get('[data-qa="continue-button"]').click().should('be.visible')

  })

it('verify login with valid credentials', ()=> {
cy.visit('https://automationexercise.com/login')
cy.get('[data-qa="login-email"]').type('mine@hee.com').should('be.visible').and('be.empty')
cy.get('[data-qa="login-password"]').type('elijah1234').should('be.visible').and('be.empty')
cy.get('[data-qa="login-button"]').click().should('be.visible')
cy.get('.features_items > :nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn')
.should('be.visible').click({ force: true })
cy.get(':nth-child(4) > .product-image-wrapper > .single-products > .productinfo > .btn')
.should('be.visible').click({ force: true })
cy.get(':nth-child(7) > .product-image-wrapper > .single-products > .productinfo > .btn')
.should('be.visible').click({ force: true })
cy.get(':nth-child(9) > .product-image-wrapper > .single-products > .productinfo > .btn')
.should('be.visible').click({ force: true })
cy.get(':nth-child(10) > .product-image-wrapper > .single-products > .productinfo > .btn')
.should('be.visible').click({ force: true })
cy.get('u').click().should('be.visible')  
cy.get('.col-sm-6 > .btn').click().should('be.visible')
cy.get('[name="message"]').type('Thank you for shopping boss').should('be.visible')
cy.get(':nth-child(7) > .btn').click().should('be.visible')
cy.get('[data-qa="name-on-card"]').type('Elijah Young').should('be.visible')
cy.get('[data-qa="card-number"]').type('1234567890').should('be.visible')
cy.get('[data-qa="cvc"]').type('009').should('be.visible')
cy.get('[data-qa="expiry-month"]').type('05').should('be.visible')
cy.get('[data-qa="expiry-year"]').type('1990').should('be.visible')
cy.get('[data-qa="pay-button"]').click().should('be.visible')
cy.get('[data-qa="continue-button"]').click().should('be.visible')

})

})